# Copyright (C) 2001-2023  Cyril Huang, Gyoza Workshop
# SPDX-License-Identifier: MIT OR Apache-2.0

doc             := latex beamer
CHAPTER         := latex.tex tex.tex install.tex packages.tex advance.tex \
                   math.tex graphics.tex beamer.tex
include         ../common.mk
