# Copyright (C) 2001-2023  Cyril Huang, Gyoza Workshop
# SPDX-License-Identifier: MIT OR Apache-2.0

doc             := opentoolsv2
CHAPTER         := opentoolsv2.tex editor.tex srm.tex compiler.tex \
                   analyser.tex debug.tex build.tex devops.tex package.tex \
                   testing.tex
include	        ../common.mk
