# Copyright (C) 2001-2023  Cyril Huang, Gyoza Workshop
# SPDX-License-Identifier: MIT OR Apache-2.0

doc             := scripts
CHAPTER         := awk.tex bash.tex comparison.tex javascript.tex \
                   perl.tex python.tex regex.tex sed.tex
include	        ../common.mk
